name: moviephoria
description: Movie Flutter Project

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

#Dependencies
dependencies:
  flutter:
    sdk: flutter

  sqflite: ^2.0.2
  cupertino_icons: ^1.0.2
  splash_screen_view: ^3.0.0
  path_provider: ^2.0.9
  http: ^0.13.4
  youtube_player_flutter: ^8.0.0
  flutter_rating_bar: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

#Splash Screen View
splash_screen_view:
  color: "#ffffff"
  image: assets/images/popcorn.png

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

#Assets
  assets:
    - assets/images/popcorn.png
    - assets/images/error.png
    - assets/images/loading.gif

#Fonts
  fonts:
    - family: Aestethicc
      fonts:
        - asset: assets/fonts/Aestethicc/Aestethicc.otf
    - family: Candara
      fonts:
        - asset: assets/fonts/Candara/Candara_Bold_Italic.ttf
        - asset: assets/fonts/Candara/Candara_Bold.ttf
        - asset: assets/fonts/Candara/Candara_Italic.ttf
        - asset: assets/fonts/Candara/Candara.ttf
    - family: Inlanders
      fonts:
        - asset: assets/fonts/Inlanders/Inlanders.otf
